// Blog article content library
// Each article has full SEO metadata + structured content blocks

export type ContentBlock =
  | { type: "paragraph"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "bullets"; items: string[] }
  | { type: "numbered"; items: string[] }
  | { type: "table"; headers: string[]; rows: string[][] }
  | { type: "callout"; variant: "tip" | "warning" | "info"; title: string; text: string }
  | { type: "faq"; items: { q: string; a: string }[] }

export type BlogArticle = {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  category: string;
  categoryLabel: string;
  author: string;
  authorTitle: string;
  date: string;
  dateModified: string;
  readTime: string;
  tags: string[];
  featured?: boolean;
  highlight?: string;
  excerpt: string;
  image: string;
  content: ContentBlock[];
  faqs: { q: string; a: string }[];
  relatedSlugs: string[];
};

export const BLOG_ARTICLES: BlogArticle[] = [
  {
    slug: "how-to-choose-variable-speed-pool-pump-commercial",
    title: "How to Choose the Right Variable Speed Pool Pump for Commercial Applications",
    metaTitle: "How to Choose a Variable Speed Pool Pump for Commercial Pools | Pool Supply Wholesalers",
    metaDescription: "Step-by-step guide to selecting the right variable speed pool pump for commercial applications. Covers TDH calculation, model comparisons, and DOE compliance. Written by pool equipment experts.",
    keywords: ["variable speed pool pump", "commercial pool pump", "how to choose pool pump", "Pentair IntelliFloXF", "Hayward TriStar VS", "TDH calculation pool pump", "DOE pool pump mandate"],
    category: "pumps",
    categoryLabel: "Pool Pumps",
    author: "Pool Supply Wholesalers",
    authorTitle: "Commercial Pool Equipment Specialists",
    date: "2026-09-01",
    dateModified: "2026-09-04",
    readTime: "8 min read",
    tags: ["variable speed pump", "commercial pool pump", "Pentair IntelliFloXF", "Hayward TriStar", "TDH calculation"],
    featured: true,
    highlight: "Code-Required in 38 States",
    excerpt: "Variable speed pumps are now code-required in most US states. Learn how to calculate total dynamic head (TDH), select the correct horsepower, and compare Pentair IntelliFloXF, Hayward TriStar VS, and Jandy FloPro VS — the top three commercial variable speed pumps.",
    image: "/images/blog/how-to-choose-variable-speed-pool-pump-commercial.jpg",
    content: [
      { type: "paragraph", text: "If you're still specifying single-speed pumps for commercial pool builds, you're behind the times — and potentially out of code. Since 2021, the US Department of Energy mandates variable speed pumps for most new installations and replacements over 1 HP. But choosing the right variable speed pump for a commercial application isn't as simple as picking the cheapest model. Get it wrong and you'll have an undersized pump struggling against high resistance, or an oversized one that never dials down enough to save meaningful energy." },
      { type: "h2", text: "Why Variable Speed Pumps Are Required (and Worth It)" },
      { type: "paragraph", text: "Variable speed pumps (VSPs) use a permanent magnet motor that can operate anywhere from 600 to 3,450 RPM. Single speed motors always run at full RPM — burning full electricity whether the pool needs it or not. The physics of fluid dynamics means that cutting pump speed in half reduces energy draw by roughly 87%. Run a 3-HP pump at 1,750 RPM instead of 3,450 RPM and you'll use a fraction of the electricity. For commercial operators running pumps 12–24 hours a day, that's thousands of dollars per year." },
      { type: "callout", variant: "info", title: "DOE Compliance Note", text: "As of July 19, 2021, all pool pump motors ≥1 HP sold in the US for residential pools must meet ENERGY STAR variable speed requirements. Most states have adopted similar or stricter rules for commercial applications. Check your local building code before specifying any single-speed pump." },
      { type: "h2", text: "Step 1: Calculate Your Total Dynamic Head (TDH)" },
      { type: "paragraph", text: "TDH is the total resistance the pump must overcome to move water through your system. It's the single most important number for pump selection, and it's where most contractors make mistakes. Too many people just grab a pump that 'sounds right' for the pool size without actually running the numbers." },
      { type: "paragraph", text: "TDH has two components: static head (elevation difference between pump and water surface) and friction head (resistance from pipes, fittings, valves, and equipment). For most commercial pools, friction head dominates." },
      { type: "numbered", items: [
        "Measure all pipe runs and note pipe diameter (2\" and 2.5\" are most common)",
        "Add equivalent pipe length for every elbow, valve, and tee (use the manufacturer's friction loss tables)",
        "Add equipment head loss: a typical commercial cartridge filter adds 5–12 ft TDH; heaters add 3–8 ft; UV systems add 2–5 ft",
        "Add static head if your pump is below or above the water level",
        "Sum everything — your total is the TDH at your target flow rate (GPM)"
      ]},
      { type: "callout", variant: "tip", title: "Pro Tip", text: "Most commercial pools run best at 30–50 GPM per pump for standard filtration cycles. Size your TDH at your target flow rate, then verify the pump's performance curve shows it can deliver that flow at that head without cavitating." },
      { type: "h2", text: "Step 2: Choose the Right Horsepower" },
      { type: "paragraph", text: "For commercial pools, resist the temptation to oversize. A pump with excess horsepower that can't dial down effectively wastes energy even at lower speeds. A properly sized variable speed pump should run at 60–80% of its max speed during filtration to save meaningful energy while maintaining adequate turnover." },
      { type: "table", headers: ["Pool Volume", "Recommended Flow Rate", "Suggested HP Range", "Daily Turnover (8hr)"], rows: [
        ["10,000–20,000 gal", "30–40 GPM", "1.0–1.5 HP VS", "1.5–2x"],
        ["20,000–50,000 gal", "40–70 GPM", "1.5–2.0 HP VS", "1.5–2x"],
        ["50,000–100,000 gal", "70–120 GPM", "2.0–3.0 HP VS", "1.5–2x"],
        ["100,000+ gal", "Multiple pumps recommended", "3.0+ HP VS x2", "1.5–2x"],
      ]},
      { type: "h2", text: "Top 3 Commercial Variable Speed Pumps Compared" },
      { type: "paragraph", text: "Once you know your TDH and target GPM, it comes down to model selection. Here are the three pumps we see in most commercial builds:" },
      { type: "table", headers: ["Model", "Max HP", "Max Flow", "Motor Type", "Warranty", "Best For"], rows: [
        ["Pentair IntelliFloXF", "3.0 HP", "140 GPM", "TEFC Perm. Magnet", "3 years", "High-flow commercial, spas"],
        ["Hayward TriStar VS", "1.85 HP", "106 GPM", "TEFC Perm. Magnet", "3 years", "Mid-size commercial, efficiency"],
        ["Jandy FloPro VS", "2.0 HP", "120 GPM", "TEFC Perm. Magnet", "3 years", "New builds, Jandy systems"],
        ["Pentair IntelliFlo3 VSF", "1.5 HP", "90 GPM", "TEFC Perm. Magnet", "3 years", "Residential/small commercial"],
      ]},
      { type: "h3", text: "Pentair IntelliFloXF — Best for High-Flow Commercial" },
      { type: "paragraph", text: "The IntelliFloXF is Pentair's flagship commercial variable speed pump, rated up to 140 GPM and 3.0 HP. It runs on a TEFC (totally enclosed fan-cooled) permanent magnet motor that's significantly more efficient than older motor designs. The built-in controller supports up to 8 programmable speed settings and integrates natively with Pentair EasyTouch and IntelliConnect automation. If you're building a 50,000+ gallon commercial pool and want everything from one brand, this is your pump." },
      { type: "h3", text: "Hayward TriStar VS — Best Balance of Price and Performance" },
      { type: "paragraph", text: "The TriStar VS offers excellent efficiency in a durable commercial frame. It integrates with the Hayward OmniLogic automation system and has a straightforward programmable interface. At a price point typically 10–15% below the IntelliFloXF, it's the most specified commercial variable speed pump in the US by unit volume. The 1.85 HP version is sufficient for most pools up to 75,000 gallons." },
      { type: "h3", text: "Jandy FloPro VS — Best for Jandy Ecosystem Builds" },
      { type: "paragraph", text: "If you're specifying Jandy heaters and AquaLink automation, the FloPro VS integrates seamlessly. The 2.0 HP version hits 120 GPM, covering most commercial applications. Jandy's variable speed platform has matured significantly in recent years, and their dealer support network is strong in Florida, California, and Texas markets." },
      { type: "h2", text: "Common Mistakes to Avoid" },
      { type: "bullets", items: [
        "Sizing pump to pool volume instead of TDH and flow rate",
        "Selecting a pump without checking the performance curve at your actual TDH",
        "Installing a 3-HP pump where a 1.5-HP would do — bigger isn't better with VSPs",
        "Forgetting to verify local code for commercial turnover rate requirements (often 6-hour turnover minimum)",
        "Specifying a residential VSP for a commercial application — look for commercial-rated models with TEFC motors",
      ]},
      { type: "h2", text: "Where to Buy at Wholesale Pricing" },
      { type: "paragraph", text: "All three pumps — Pentair IntelliFloXF, Hayward TriStar VS, and Jandy FloPro VS — are available through Pool Supply Wholesalers at direct wholesale to retail pricing, typically 20–35% below standard retail MSRP. We ship same-day from distribution hubs in Nashville TN, Los Angeles CA, Dallas TX, and Orlando FL. Open a commercial trade account for priority fulfillment and volume pricing on multi-pump projects." },
    ],
    faqs: [
      { q: "Are variable speed pumps required for commercial pools?", a: "Most US states now require variable speed pumps for new commercial pool installations and pump replacements. The DOE mandate covers pools over 1 HP. Check your local building code as some states (California, Texas, Florida) have additional requirements beyond federal minimums." },
      { q: "How much can I save with a variable speed pump?", a: "On average, commercial pool operators save 70–90% on pump operating costs compared to single-speed pumps. A 3-HP single-speed pump running 24/7 can cost $3,000–$5,000/year in electricity. The same capacity in a variable speed pump at optimized speeds typically costs $400–$800/year." },
      { q: "What's the difference between IntelliFloXF and IntelliFloVSF?", a: "The IntelliFloXF is Pentair's commercial-grade pump with higher flow capacity (140 GPM) and a TEFC motor for outdoor commercial use. The IntelliFlo VSF (Variable Speed + Flow) is a residential-grade pump with integrated flow meter but lower max GPM. Commercial applications should use the XF." },
    ],
    relatedSlugs: ["top-10-signs-pool-pump-motor-needs-replacement", "pool-automation-systems-explained-2026", "commercial-pool-equipment-checklist-complete-build-supply-list"],
  },
  {
    slug: "pentair-vs-hayward-vs-jandy-pool-heater-comparison-2026",
    title: "Pentair vs Hayward vs Jandy: Complete Pool Heater Comparison 2026",
    metaTitle: "Pentair vs Hayward vs Jandy Pool Heater Comparison 2026 | Pool Supply Wholesalers",
    metaDescription: "Side-by-side comparison of Pentair MasterTemp 400, Hayward H400FDN, and Jandy JXi 400 pool heaters. BTU output, efficiency, warranty, and commercial use guide from certified distributors.",
    keywords: ["Pentair MasterTemp 400", "Hayward H400FDN", "Jandy JXi 400", "pool heater comparison 2026", "gas pool heater", "BTU pool heater", "commercial pool heater"],
    category: "heaters",
    categoryLabel: "Heaters",
    author: "Pool Supply Wholesalers",
    authorTitle: "Commercial Pool Equipment Specialists",
    date: "2026-08-28",
    dateModified: "2026-09-04",
    readTime: "11 min read",
    tags: ["Pentair MasterTemp", "Hayward H400", "Jandy JXi", "pool heater comparison", "BTU pool heater"],
    highlight: "Head-to-Head Specs",
    excerpt: "Side-by-side breakdown of Pentair MasterTemp 400, Hayward H400FDN, and Jandy Pro Series JXi 400 — covering BTU output, energy efficiency ratings, ignition systems, warranty coverage, and commercial applications.",
    image: "/images/blog/pentair-vs-hayward-vs-jandy-pool-heater-comparison-2026.jpg",
    content: [
      { type: "paragraph", text: "Picking a pool heater sounds straightforward until you're standing in front of three equally impressive options from Pentair, Hayward, and Jandy — all within 10% of the same price. The truth is, for 90% of commercial applications, all three will heat your pool reliably for 10+ years. The real differences come down to efficiency ratings, ignition reliability, integration with your automation system, and what your local service techs know best." },
      { type: "h2", text: "Gas vs. Heat Pump: A Quick Note" },
      { type: "paragraph", text: "This guide focuses on natural gas and propane heaters, which are still the standard for commercial pools because of their fast heat-up time (typically 2–4°F per hour on a large commercial pool). Heat pump heaters are more efficient in warm climates but have COP limitations below 50°F ambient air. For most commercial aquatic facilities that need reliable heating in all seasons, gas is the standard." },
      { type: "h2", text: "Head-to-Head Comparison: 400K BTU Models" },
      { type: "table", headers: ["Spec", "Pentair MasterTemp 400", "Hayward H400FDN", "Jandy JXi 400"], rows: [
        ["BTU Output", "400,000", "400,000", "399,000"],
        ["Thermal Efficiency", "84%", "83%", "84%"],
        ["Fuel Type", "NG or LP", "NG or LP", "NG or LP"],
        ["Min Gas Pressure (NG)", "4\" W.C.", "3.5\" W.C.", "4\" W.C."],
        ["Ignition Type", "Electronic (no pilot)", "Electronic (no pilot)", "Electronic (no pilot)"],
        ["Low NOx", "Yes (SCAQMD compliant)", "Yes (SCAQMD compliant)", "Yes (SCAQMD compliant)"],
        ["Max Water Flow", "100 GPM", "125 GPM", "125 GPM"],
        ["Cabinet Material", "Polymer (corrosion-resistant)", "Polymer", "Stainless Steel"],
        ["Warranty (residential)", "3 years parts, 1 year labor", "3 years parts, 1 year labor", "3 years parts, 1 year labor"],
        ["Warranty (commercial)", "1 year parts and labor", "1 year parts and labor", "1 year parts and labor"],
        ["Display", "Digital LED", "Digital LCD", "Digital LED"],
        ["Automation Integration", "Pentair EasyTouch/IntelliConnect", "Hayward OmniLogic", "Jandy AquaLink RS"],
      ]},
      { type: "h2", text: "Pentair MasterTemp 400 — Best for Pentair Ecosystem Builds" },
      { type: "paragraph", text: "The MasterTemp 400 is one of the most-installed commercial pool heaters in the country, and for good reason. Its polymer cabinet resists salt air corrosion better than competitors, the digital interface is intuitive, and service techs in every major market know this unit inside and out. The MasterTemp uses a cupro-nickel heat exchanger as standard on the commercial version, which is critical in saltwater pool installations where copper deteriorates quickly." },
      { type: "paragraph", text: "Integration with Pentair's EasyTouch and IntelliConnect automation is seamless — the heater communicates via serial protocol and shows up on your automation panel without additional wiring. If you're already specifying Pentair pumps and automation, the MasterTemp is the natural choice." },
      { type: "h2", text: "Hayward H400FDN — Best for High Water Flow Systems" },
      { type: "paragraph", text: "The H400FDN edges out the competition in one important spec: it supports up to 125 GPM water flow versus the MasterTemp's 100 GPM. On large commercial pools with high-flow circulation systems (common in water parks and resort pools), this matters. Undersizing the water flow spec can cause nuisance high-temp shutdowns during peak demand." },
      { type: "paragraph", text: "Hayward also has one of the most extensive service networks in the industry, with certified technicians in every major US market. If you're building in a market where Pentair service is harder to find, Hayward is often the better long-term maintenance choice. The H400FDN's LCD display is slightly less intuitive than Pentair's LED interface, but it's perfectly functional." },
      { type: "h2", text: "Jandy JXi 400 — Best Build Quality" },
      { type: "paragraph", text: "The JXi stands out with its stainless steel cabinet — a meaningful durability advantage in coastal or high-humidity environments where polymer cabinets can fade and crack over 5–10 years. The JXi also matches Hayward's 125 GPM max flow rating and uses the same 84% thermal efficiency as the MasterTemp." },
      { type: "paragraph", text: "Jandy's weakness has historically been parts availability in smaller markets. If you're building in Miami, Los Angeles, Phoenix, or Dallas, you'll find plenty of Jandy service infrastructure. In secondary markets, Pentair and Hayward tend to have broader parts distribution." },
      { type: "h2", text: "How to Size a Pool Heater" },
      { type: "paragraph", text: "For commercial pools, the standard sizing formula is: BTU needed = Pool Volume (gallons) × 8.34 (lb/gal) × Temperature Rise (°F) × Heat Load Factor." },
      { type: "callout", variant: "tip", title: "Quick Commercial Sizing Rule", text: "As a rough rule, plan for approximately 6,000–8,000 BTU per 1,000 gallons of pool volume for an uncovered outdoor commercial pool in temperate US climates. A 100,000-gallon hotel pool typically requires a 400,000–600,000 BTU heater (or multiple units)." },
      { type: "h2", text: "Which Heater Should You Choose?" },
      { type: "bullets", items: [
        "Pentair EasyTouch or IntelliConnect automation → Pentair MasterTemp 400",
        "Hayward OmniLogic automation → Hayward H400FDN",
        "Jandy AquaLink RS automation → Jandy JXi 400",
        "Saltwater pool → Any model with cupro-nickel heat exchanger (confirm before ordering)",
        "Coastal/high-humidity environment → Jandy JXi (stainless steel cabinet advantage)",
        "High water flow system (>100 GPM) → Hayward H400FDN or Jandy JXi",
      ]},
    ],
    faqs: [
      { q: "What's the most reliable pool heater for commercial use?", a: "Pentair MasterTemp, Hayward H-Series, and Jandy JXi all have strong commercial reliability records when properly sized and maintained. The best choice typically depends on your automation system and local service availability. All three carry 1-year commercial warranties." },
      { q: "Do I need a cupro-nickel heat exchanger for a saltwater pool?", a: "Yes, for saltwater pools you should specify the cupro-nickel heat exchanger option (vs. standard copper). Salt water degrades copper heat exchangers significantly faster, leading to premature failure within 3–5 years. Most commercial versions of the MasterTemp, H400, and JXi offer cupro-nickel as standard or an upgrade." },
      { q: "How much does it cost to run a 400,000 BTU pool heater?", a: "At an average US natural gas rate of $1.10/therm, a 400,000 BTU heater at 84% efficiency consumes roughly 4.76 therms per hour of full operation. That's approximately $5.24/hour. Most commercial pools don't run the heater continuously — demand depends on ambient temp, pool cover use, and bather load." },
    ],
    relatedSlugs: ["how-to-choose-variable-speed-pool-pump-commercial", "pool-automation-systems-explained-2026", "commercial-pool-equipment-checklist-complete-build-supply-list"],
  },
  {
    slug: "cartridge-filter-vs-sand-filter-pool-contractor-guide",
    title: "Cartridge Filter vs Sand Filter: Pool Contractor's Complete Guide",
    metaTitle: "Cartridge Filter vs Sand Filter for Commercial Pools | Pool Supply Wholesalers",
    metaDescription: "Cartridge filter vs sand filter: which is right for your commercial pool project? Full comparison of filtration levels, water usage, maintenance, and cost. Includes sizing charts.",
    keywords: ["cartridge filter vs sand filter", "commercial pool filter", "pool filter comparison", "pool filtration guide", "pool filter sizing", "cartridge pool filter", "sand pool filter"],
    category: "filters",
    categoryLabel: "Filters",
    author: "Pool Supply Wholesalers",
    authorTitle: "Commercial Pool Equipment Specialists",
    date: "2026-08-20",
    dateModified: "2026-09-04",
    readTime: "7 min read",
    tags: ["cartridge filter", "sand filter", "pool filter comparison", "pool filtration guide", "commercial pool filter"],
    highlight: "Sizing Charts Included",
    excerpt: "Which filtration system is right for your project? We break down micron filtration levels, backwash requirements, water usage, maintenance intervals, and total cost of ownership for commercial pools.",
    image: "/images/blog/cartridge-filter-vs-sand-filter-pool-contractor-guide.jpg",
    content: [
      { type: "paragraph", text: "The filter vs filter debate comes up in almost every commercial pool spec meeting. Owners want the cheapest option; engineers want the lowest maintenance; health departments want the cleanest water. The right answer depends on your specific site conditions — and it's almost never one-size-fits-all." },
      { type: "h2", text: "How Each Filter Technology Works" },
      { type: "h3", text: "Cartridge Filters" },
      { type: "paragraph", text: "Cartridge filters use pleated polyester filter elements (cartridges) to physically strain particles from water as it passes through. The pleated design dramatically increases surface area — a 520 sq ft Pentair Clean & Clear Plus, for example, has more filter area than a comparably sized sand filter at a fraction of the water waste." },
      { type: "h3", text: "Sand Filters" },
      { type: "paragraph", text: "Sand filters push water through a bed of #20 silica sand (or newer zeolite/glass media). Particles get trapped in the sand bed as water passes downward. When pressure builds, you backwash — reversing flow to flush trapped debris to waste. The process takes 2–4 minutes but wastes 100–200+ gallons of backwash water per cycle." },
      { type: "h2", text: "Filtration Comparison: What Actually Gets Filtered" },
      { type: "table", headers: ["Filter Type", "Filtration Level", "What Gets Through", "Clarity Result"], rows: [
        ["Cartridge (standard)", "10–15 microns", "Fine oils, some bacteria", "Very clear — health code compliant"],
        ["Sand (silica)", "20–40 microns", "Fine particles, algae spores", "Clear but slightly hazy possible"],
        ["Sand (zeolite media)", "3–5 microns", "Most particles, ammonia", "Comparable to cartridge"],
        ["DE (diatomaceous earth)", "1–3 microns", "Near-total particle removal", "Crystal clear"],
      ]},
      { type: "paragraph", text: "For most commercial pools with strict health code requirements, cartridge filters at 10–15 microns provide excellent clarity without the water waste of backwashing. They're now the preferred choice for high-traffic commercial pools in California and Florida." },
      { type: "h2", text: "Water Usage: A Critical Commercial Consideration" },
      { type: "paragraph", text: "This is where cartridge filters win decisively for water-conscious operations. Sand filters need backwashing every 2–4 weeks typically, using 150–250 gallons per backwash cycle. A busy commercial pool might need backwashing twice weekly — that's 300–500 gallons per week, or 15,000–26,000 gallons per year just in backwash water. At commercial water rates, that adds up fast." },
      { type: "callout", variant: "info", title: "Water Cost Example", text: "At $0.005 per gallon commercial water rate, backwashing a large sand filter twice weekly costs approximately $75–$130/year in water costs alone — plus chemicals to replace what's lost and the labor to backwash. Cartridge filters require no backwash water." },
      { type: "h2", text: "Maintenance Comparison" },
      { type: "table", headers: ["Task", "Cartridge Filter", "Sand Filter"], rows: [
        ["Routine cleaning", "Rinse cartridges every 6–12 weeks", "Backwash every 2–4 weeks"],
        ["Deep cleaning", "Soak cartridges in cleaner 2x/year", "Not required"],
        ["Media replacement", "Cartridges every 2–3 years ($150–400)", "Sand every 5–7 years ($80–200)"],
        ["Water usage", "Zero (no backwash)", "150–250 gal per backwash cycle"],
        ["Labor per maintenance", "20–45 minutes", "5–10 minutes per backwash"],
      ]},
      { type: "h2", text: "Filter Sizing Guide for Commercial Pools" },
      { type: "paragraph", text: "The golden rule for sizing: calculate at 1 sq ft of filter area per 10 GPM of flow rate (cartridge), or 1 sq ft of sand bed area per 15–20 GPM (sand). Under-sizing causes rapid pressure buildup and poor filtration. Commercial pools should always be sized at the larger end of the range." },
      { type: "table", headers: ["Pool Volume", "Flow Rate (GPM)", "Cartridge Filter Size", "Sand Filter Size"], rows: [
        ["25,000 gal", "30–40 GPM", "400–520 sq ft", "2.5–3 sq ft sand bed"],
        ["50,000 gal", "50–70 GPM", "520–700 sq ft", "3–4 sq ft sand bed"],
        ["100,000 gal", "80–120 GPM", "800–1,200 sq ft (multiple units)", "5–7 sq ft (large commercial unit)"],
      ]},
      { type: "h2", text: "Top Models by Category" },
      { type: "h3", text: "Best Cartridge Filters" },
      { type: "bullets", items: [
        "Pentair Clean & Clear Plus 520 — most-specified commercial cartridge filter, 520 sq ft",
        "Hayward C7030 Star-Clear Plus — 700 sq ft capacity for large commercial applications",
        "Jandy DEV600 — DE filter option for maximum clarity in high-inspection facilities",
      ]},
      { type: "h3", text: "Best Sand Filters" },
      { type: "bullets", items: [
        "Hayward Pro Series Sand Filter — most widely serviced commercial sand filter in the US",
        "Pentair Tagelus TA-100D — large commercial single-unit sand filter",
        "Jandy CS Series — strong performer for Jandy ecosystem builds",
      ]},
      { type: "h2", text: "Our Recommendation for Commercial Pools" },
      { type: "paragraph", text: "For most commercial pool applications — hotel pools, apartment complexes, aquatic centers, and health clubs — we recommend cartridge filtration. The water clarity is better, water usage is zero, and modern cartridge elements last 2–3 years between replacements. Yes, the upfront cost is higher, but the total cost of ownership over 5 years is comparable or better when you factor in water savings and labor." },
    ],
    faqs: [
      { q: "Can I upgrade from a sand filter to a cartridge filter on an existing commercial pool?", a: "Yes, in most cases this is a straightforward equipment swap. You'll need to verify the plumbing connections match (most commercial filters use 2\" or 2.5\" PVC), and confirm the new filter's flow rate range is compatible with your existing pump. Pool Supply Wholesalers can help spec the right replacement." },
      { q: "How often do commercial pool cartridge filters need to be replaced?", a: "Commercial pool cartridge filter elements typically last 2–3 years with proper maintenance (rinsing every 6–8 weeks and chemical soaking 2x/year). In very high-bather-load facilities (water parks, competition pools), plan for replacement every 18–24 months." },
    ],
    relatedSlugs: ["how-to-choose-variable-speed-pool-pump-commercial", "how-to-size-pool-salt-chlorinator", "commercial-pool-equipment-checklist-complete-build-supply-list"],
  },
  {
    slug: "pool-automation-systems-explained-2026",
    title: "Pool Automation Systems Explained: IntelliConnect vs EasyTouch vs AquaLink vs OmniLogic",
    metaTitle: "Pool Automation Systems Compared 2026: IntelliConnect vs EasyTouch vs AquaLink vs OmniLogic",
    metaDescription: "Full breakdown of the top pool automation systems for commercial pools. Compare Pentair IntelliConnect, EasyTouch, Jandy AquaLink RS, and Hayward OmniLogic on circuit capacity, app features, and installation complexity.",
    keywords: ["pool automation systems", "Pentair IntelliConnect", "Pentair EasyTouch", "Jandy AquaLink RS", "Hayward OmniLogic", "smart pool system", "commercial pool automation"],
    category: "automation",
    categoryLabel: "Automation",
    author: "Pool Supply Wholesalers",
    authorTitle: "Commercial Pool Equipment Specialists",
    date: "2026-08-14",
    dateModified: "2026-09-04",
    readTime: "9 min read",
    tags: ["pool automation", "Pentair IntelliConnect", "EasyTouch", "Jandy AquaLink", "smart pool system"],
    highlight: "Smart Pool Integration",
    excerpt: "Compare Pentair IntelliConnect, Pentair EasyTouch, Jandy AquaLink RS, and Hayward OmniLogic — covering circuit capacity, mobile app features, third-party integration, and installation complexity for commercial builds.",
    image: "/images/blog/pool-automation-systems-explained-2026.jpg",
    content: [
      { type: "paragraph", text: "Pool automation has gone from a luxury to an expectation. Hotel guests want to control the hot tub from their phone; facility managers want energy reports and equipment alerts without walking to the equipment room; and health inspectors want logged data on sanitizer levels and pump run-times. The right automation system makes all of this possible — and the wrong choice creates years of integration headaches." },
      { type: "h2", text: "What Pool Automation Actually Controls" },
      { type: "bullets", items: [
        "Pump speed and schedules (variable speed pump integration)",
        "Heater setpoints and on/off scheduling",
        "Light color, intensity, and show sequences (for LED systems)",
        "Water features (waterfalls, deck jets, bubblers)",
        "Salt chlorinator output levels",
        "Chemical dosing system triggers",
        "Pool vs. spa mode switching",
        "Remote alerts for equipment faults",
      ]},
      { type: "h2", text: "The Four Major Commercial Automation Platforms" },
      { type: "table", headers: ["System", "Max Circuits", "App Quality", "VS Pump Integration", "Third-Party Devices", "Best For"], rows: [
        ["Pentair IntelliConnect", "8 circuits", "Excellent (Pentair Home)", "Native IntelliFlo", "Limited", "Small commercial, easy setup"],
        ["Pentair EasyTouch", "40 circuits", "Good (ScreenLogic)", "Native IntelliFlo", "Moderate", "Large commercial, multi-pool"],
        ["Jandy AquaLink RS", "32 circuits", "Good (iAquaLink)", "Native FloPro VS", "Good", "Jandy ecosystem, resort pools"],
        ["Hayward OmniLogic", "40 circuits", "Best-in-class", "Native TriStar VS", "Excellent", "Tech-forward facilities, hotel pools"],
      ]},
      { type: "h2", text: "Pentair IntelliConnect — Best for Simpler Commercial Applications" },
      { type: "paragraph", text: "IntelliConnect is Pentair's newer, more affordable automation entry that controls up to 8 circuits via a sleek touchscreen panel. Setup is genuinely faster than traditional hardwired systems — most installations are done in under 4 hours. The Pentair Home app is polished and responds quickly to commands. The limitation is the 8-circuit cap, which is fine for a single pool/spa combination but won't scale to complex multi-feature aquatic facilities." },
      { type: "h2", text: "Pentair EasyTouch — Best for Complex Multi-Circuit Commercial Builds" },
      { type: "paragraph", text: "EasyTouch is Pentair's full commercial-grade automation platform, supporting up to 40 circuits across multiple pools, spas, and water features. The ScreenLogic interface (web browser + app) gives facility managers a desktop-friendly control panel that health inspectors and engineers appreciate. Native integration with IntelliFlo pumps, MasterTemp heaters, and IntelliChlor salt systems makes it the natural choice for all-Pentair builds." },
      { type: "callout", variant: "tip", title: "Installation Tip", text: "EasyTouch wiring is straightforward for experienced pool contractors but requires careful load center layout for 40-circuit installations. Budget 6–8 hours for a full 40-circuit commercial installation, plus programming time." },
      { type: "h2", text: "Hayward OmniLogic — Best Mobile App and Third-Party Integration" },
      { type: "paragraph", text: "OmniLogic consistently wins comparisons on mobile app quality. The Hayward OmniLogic app is fast, visually clear, and reliably maintains connection — common pain points with competitor apps. It also supports the broadest range of third-party integrations: Amazon Alexa, Google Home, IFTTT, and multiple building management systems. For hotel or resort applications where the pool system needs to integrate with broader building automation, OmniLogic's open ecosystem is a major advantage." },
      { type: "h2", text: "Jandy AquaLink RS — Best for Jandy Equipment Builds" },
      { type: "paragraph", text: "AquaLink RS is the control backbone of Jandy's ecosystem and supports up to 32 circuits with serial communication to FloPro VS pumps, JXi heaters, and AquaPure salt systems. The iAquaLink app is solid but not quite as polished as OmniLogic. Where Jandy excels is in multi-pool resort facilities — AquaLink RS can manage multiple equipment pads from a single control point, which is why it's dominant in large Florida and California resort accounts." },
      { type: "h2", text: "How to Choose" },
      { type: "numbered", items: [
        "Identify your primary equipment brands (Pentair/Hayward/Jandy) — stay in ecosystem for cleanest integration",
        "Count your total circuits needed (each pump, each light zone, heater, cleaner, and water feature is typically one circuit)",
        "Determine your mobile/remote access requirements — if the app quality is critical, OmniLogic wins",
        "Check third-party integration needs — building management systems favor OmniLogic or EasyTouch",
        "Factor in installer familiarity — automation is only as good as the programmer setting it up",
      ]},
    ],
    faqs: [
      { q: "Can I use Hayward OmniLogic to control a Pentair pump?", a: "Technically possible with adapter cables, but not recommended. Cross-brand automation integration typically loses advanced features like variable speed control and fault diagnostics. Staying within one brand's ecosystem gives you native serial communication, better reliability, and full warranty support." },
      { q: "Do pool automation systems work with Alexa or Google Home?", a: "Hayward OmniLogic has the best third-party smart home integration, supporting Amazon Alexa and Google Home natively. Pentair IntelliConnect and EasyTouch support Alexa through the Pentair Home app. Jandy iAquaLink supports Amazon Alexa but not Google Home as of 2026." },
    ],
    relatedSlugs: ["how-to-choose-variable-speed-pool-pump-commercial", "pentair-vs-hayward-vs-jandy-pool-heater-comparison-2026", "commercial-pool-equipment-checklist-complete-build-supply-list"],
  },
  {
    slug: "how-to-size-pool-salt-chlorinator",
    title: "How to Size a Pool Salt Chlorinator: Step-by-Step Guide for Contractors",
    metaTitle: "How to Size a Pool Salt Chlorinator: Step-by-Step Guide | Pool Supply Wholesalers",
    metaDescription: "Learn how to size a salt chlorinator for commercial and residential pools. Covers output calculations, bather load adjustments, and model comparisons for Pentair IntelliChlor, Hayward AquaRite, and Jandy AquaPure.",
    keywords: ["salt chlorinator sizing", "how to size salt chlorinator", "IntelliChlor IC60", "Hayward T-CELL-15", "Jandy AquaPure 1400", "salt system guide", "commercial pool salt chlorinator"],
    category: "salt",
    categoryLabel: "Salt Systems",
    author: "Pool Supply Wholesalers",
    authorTitle: "Commercial Pool Equipment Specialists",
    date: "2026-08-08",
    dateModified: "2026-09-04",
    readTime: "6 min read",
    tags: ["salt chlorinator sizing", "IntelliChlor IC60", "Hayward T-CELL", "salt system guide", "chlorinator GPH calculation"],
    highlight: "Sizing Calculator Guide",
    excerpt: "Correct chlorinator sizing directly impacts water quality, equipment longevity, and client satisfaction. This step-by-step guide covers output calculation by pool volume, bather load adjustment factors, and model comparisons.",
    image: "/images/blog/how-to-size-pool-salt-chlorinator.jpg",
    content: [
      { type: "paragraph", text: "An undersized salt chlorinator is one of the most common causes of green pool callbacks. The client blames chemistry, you blame chemistry, but the real problem is that the cell never had the capacity to keep up with the chlorine demand. Proper sizing upfront prevents this entirely." },
      { type: "h2", text: "How Salt Chlorination Works" },
      { type: "paragraph", text: "A salt chlorinator (also called a salt chlorine generator or SWG) uses electrolysis to convert dissolved sodium chloride (salt) into free chlorine. Pool water passes through the electrolytic cell, where a low-voltage current splits the NaCl molecules into hypochlorous acid — the same sanitizer as liquid chlorine. The result is continuous, automatic chlorination without manual dosing." },
      { type: "callout", variant: "info", title: "Salt Level Reference", text: "Most salt chlorinators require a salt level of 2,700–3,400 ppm in the pool water to operate efficiently. This is roughly 10% of the saltiness of ocean water — most swimmers can't taste or feel it at this level. Test salt levels monthly and add pool-grade salt (not table salt) as needed." },
      { type: "h2", text: "The Sizing Formula" },
      { type: "paragraph", text: "Salt chlorinator output is rated in grams of chlorine produced per hour (g/hr). The basic sizing formula is:" },
      { type: "numbered", items: [
        "Determine your pool volume in gallons",
        "Multiply by 0.00013 to get the minimum g/hr needed for a standard residential load (roughly 1 ppm chlorine per day maintenance dose)",
        "Multiply by 1.5 for commercial pools with moderate bather load",
        "Multiply by 2.0 for high-bather-load facilities (water parks, fitness center pools, public pools)",
        "Add 25% buffer for UV exposure, warm water, and peak demand",
      ]},
      { type: "table", headers: ["Pool Volume", "Residential (g/hr)", "Commercial Moderate (g/hr)", "Commercial High Traffic (g/hr)"], rows: [
        ["15,000 gal", "20–30 g/hr", "30–45 g/hr", "40–60 g/hr"],
        ["25,000 gal", "30–40 g/hr", "45–60 g/hr", "60–80 g/hr"],
        ["50,000 gal", "40–60 g/hr", "60–90 g/hr", "80–120 g/hr"],
        ["100,000 gal", "60–80 g/hr", "90–120 g/hr", "120–160 g/hr"],
      ]},
      { type: "h2", text: "Top Salt Chlorinators Compared" },
      { type: "table", headers: ["Model", "Output (g/hr)", "Max Pool Size", "Cell Life", "Control"], rows: [
        ["Pentair IntelliChlor IC40", "40 g/hr", "40,000 gal residential", "10,000 hrs", "Stand-alone or automation"],
        ["Pentair IntelliChlor IC60", "60 g/hr", "60,000 gal residential", "10,000 hrs", "Stand-alone or automation"],
        ["Hayward AquaRite T-CELL-15", "40 g/hr", "40,000 gal", "10,000 hrs", "Standalone or OmniLogic"],
        ["Jandy AquaPure 1400", "1,400 gal/day output", "70,000 gal", "10,000 hrs", "Standalone or AquaLink"],
        ["Hayward T-CELL-940 Commercial", "95 g/hr", "95,000 gal", "10,000 hrs", "Standalone or OmniLogic"],
      ]},
      { type: "h2", text: "Common Sizing Mistakes" },
      { type: "bullets", items: [
        "Sizing to the maximum rated pool volume — always size to 60–75% of the rated max for a buffer",
        "Ignoring bather load — a hotel pool used by 50+ people daily needs 2x the output of a residential pool",
        "Not accounting for UV exposure — outdoor pools in sunny climates (FL, CA, TX, AZ) have higher chlorine demand than shaded or indoor pools",
        "Skipping the 25% buffer — you want the cell running at 70–80% capacity, not 100%, to extend cell life",
        "Using residential-rated cells for commercial applications — commercial pools need cells rated for commercial use",
      ]},
      { type: "h2", text: "Cell Maintenance and Lifespan" },
      { type: "paragraph", text: "Salt cells typically last 7–10 years or about 10,000 operating hours under normal conditions. Premature failure is usually caused by low salt levels (the cell works harder and overheats), high calcium hardness (causes scale buildup on the plates), or operating at 100% output continuously. A well-maintained cell running at 70–80% of capacity will outlast a poorly maintained cell running at 100%." },
    ],
    faqs: [
      { q: "Can I use a residential salt chlorinator on a commercial pool?", a: "Not recommended. Residential salt chlorinators are designed for pools up to 40,000–60,000 gallons at low bather loads. Commercial pools have much higher chlorine demand due to larger volume and heavier use. Use a commercial-rated chlorinator like the Hayward T-CELL-940 or multiple residential units with a manifold system." },
      { q: "What salt level should I maintain in a commercial pool?", a: "Most commercial salt chlorinators operate optimally at 2,700–3,200 ppm salt. Test weekly with a dedicated salt test meter (not test strips, which are less accurate for salt). Add pool-grade sodium chloride as needed — never table salt or rock salt, which contain impurities." },
    ],
    relatedSlugs: ["cartridge-filter-vs-sand-filter-pool-contractor-guide", "pool-automation-systems-explained-2026", "commercial-pool-equipment-checklist-complete-build-supply-list"],
  },
  {
    slug: "top-10-signs-pool-pump-motor-needs-replacement",
    title: "Top 10 Signs Your Pool Pump Motor Needs Replacement",
    metaTitle: "Top 10 Signs Your Pool Pump Motor Needs Replacement | Pool Supply Wholesalers",
    metaDescription: "Know when to replace your pool pump motor before it fails completely. 10 clear warning signs from pool equipment experts — plus how to source OEM replacement motors fast.",
    keywords: ["pool pump motor failure", "pool pump motor replacement", "capacitor failure pool pump", "pool pump troubleshooting", "pool pump humming", "OEM pool pump parts", "signs pool pump dying"],
    category: "pumps",
    categoryLabel: "Pool Pumps",
    author: "Pool Supply Wholesalers",
    authorTitle: "Commercial Pool Equipment Specialists",
    date: "2026-08-01",
    dateModified: "2026-09-04",
    readTime: "5 min read",
    tags: ["pool pump motor failure", "pump motor replacement", "capacitor failure", "pool pump troubleshooting", "OEM pool parts"],
    highlight: "Diagnostic Checklist",
    excerpt: "Recognize early warning signs before a motor failure leaves your client with a green pool. We cover the 10 most common failure symptoms — from humming on startup to bearing noise — plus OEM part sources for fast turnaround.",
    image: "/images/blog/top-10-signs-pool-pump-motor-needs-replacement.jpg",
    content: [
      { type: "paragraph", text: "A failing pool pump motor rarely dies without warning. There are usually multiple warning signs in the weeks or months before failure — and catching them early means a planned replacement on your schedule, not an emergency service call on a Saturday with a green pool and an angry client on the phone. Here are the 10 signs we tell every service tech to watch for." },
      { type: "h2", text: "1. Motor Hums But Won't Start" },
      { type: "paragraph", text: "This is the classic capacitor failure symptom. The motor gets power (you hear the hum), but the starting capacitor has failed and can't give the motor the extra current kick it needs to get turning. On a single-speed motor, you might be able to spin the motor shaft by hand (with power off!) to get it started as a temporary fix — but that capacitor needs replacement ASAP. Capacitors are inexpensive ($15–40) and straightforward to replace." },
      { type: "h2", text: "2. Pump Trips the Breaker" },
      { type: "paragraph", text: "A pump that repeatedly trips its circuit breaker is drawing more current than normal — typically caused by a failing motor winding that's developing a short, deteriorating bearings that are creating mechanical drag, or a capacitor drawing excessive amperage at startup. Always check the actual amp draw with a clamp meter and compare to the motor's nameplate amperage. More than 10% over nameplate is a red flag." },
      { type: "h2", text: "3. Burning Smell from the Pump" },
      { type: "paragraph", text: "A hot electrical smell — like burning plastic or rubber — means motor windings are overheating. This can be caused by reduced airflow (something blocking the motor vents), a motor working too hard due to flow restriction, or insulation breaking down on aging windings. Don't ignore this. A burning smell is the motor telling you it's close to failure." },
      { type: "h2", text: "4. Grinding or Squealing Noise" },
      { type: "paragraph", text: "Pool pump motors use sealed bearings on both ends of the motor shaft. When these bearings wear, they produce a grinding, squealing, or rumbling sound that gets worse over time. Bearings are replaceable, but the labor to replace them is often similar to the cost of a new motor — do the math on whether a motor replacement makes more sense." },
      { type: "h2", text: "5. Motor Gets Excessively Hot" },
      { type: "paragraph", text: "Pool pump motors run warm — that's normal. But a motor that's too hot to touch (above 140°F) is a problem. Common causes: motor vents clogged with debris, motor running above its rated load, or failing winding insulation. A thermal cutout should protect the motor from damage, but repeated thermal trips accelerate winding deterioration." },
      { type: "h2", text: "6. Rust or Corrosion on Motor Housing" },
      { type: "paragraph", text: "Surface rust on the motor's end bells isn't necessarily fatal, but rust around the winding area or shaft seal housing indicates moisture has entered the motor internals. Once moisture reaches the windings, insulation breaks down rapidly. This is especially common in coastal installations where salt air is constant. When you see this, pull the motor and inspect it carefully." },
      { type: "h2", text: "7. Vibration or Unusual Vibration Patterns" },
      { type: "paragraph", text: "A balanced pump runs smooth. If you're feeling excessive vibration in the pump housing or nearby pipes, the pump impeller may be partially clogged, the motor bearings may be failing, or the motor shaft may have developed a bend. Vibration accelerates wear on seals, connections, and nearby plumbing — address it before it cascades into multiple repair items." },
      { type: "h2", text: "8. Low Suction or Flow Despite Clean Basket" },
      { type: "paragraph", text: "When flow drops but the pump basket is clear and there's no air in the system, a failing motor running below rated speed is often the culprit. This is especially diagnostic if you measure low voltage at the motor terminals (voltage drop on a long run can cause this) or if the motor is running hot. A variable speed pump showing lower-than-expected flow at a set RPM also warrants motor inspection." },
      { type: "h2", text: "9. Motor Shaft Seal Leaking" },
      { type: "paragraph", text: "The shaft seal separates the wet end (impeller, water) from the dry end (motor). When seals fail, water enters the motor. You'll often notice a slow leak at the pump body base before the motor shows obvious damage. Shaft seals should be replaced at first sign of leakage — it's a $15–30 part that protects a $200–600 motor." },
      { type: "h2", text: "10. Motor Age Over 10 Years" },
      { type: "paragraph", text: "Even a well-maintained pool pump motor has a finite service life. Most quality motors are designed for 8–12 years of operation. Past 10 years, the probability of failure increases significantly — winding insulation degrades, bearing wear accelerates, and capacitors age. If you're doing a service call on a motor over 10 years old, have a replacement conversation with the client regardless of whether the current issue is minor. Proactive replacement beats emergency replacement every time." },
      { type: "h2", text: "Repair vs. Replace: The Decision Framework" },
      { type: "table", headers: ["Situation", "Recommendation"], rows: [
        ["Capacitor failure only, motor < 7 years old", "Replace capacitor ($15–40 part, 30-min job)"],
        ["Bearings failing, motor < 5 years old", "Replace bearings or motor — compare labor costs"],
        ["Winding failure, any age", "Replace motor"],
        ["Motor > 10 years, any issue", "Replace motor — don't throw money at old equipment"],
        ["Shaft seal only, motor < 8 years", "Replace seal ($15–30) — high ROI"],
        ["Multiple issues on same motor", "Replace motor — don't compound repairs"],
      ]},
      { type: "h2", text: "Sourcing OEM Replacement Motors" },
      { type: "paragraph", text: "When you need a replacement motor, getting an OEM-spec motor matters. Aftermarket motors may fit the mounting dimensions but often run at different RPM, amperage, or with different enclosures — causing performance mismatches and voiding pump warranties. Pool Supply Wholesalers stocks OEM replacement motors for Pentair, Hayward, and Jandy pump frames, typically shipping same-day from our Nashville, LA, Dallas, and Orlando hubs." },
    ],
    faqs: [
      { q: "How much does it cost to replace a pool pump motor?", a: "OEM replacement pool pump motors range from $150–$500 depending on brand and HP. Single-speed motors are at the lower end; variable speed motors are significantly more expensive. Labor for replacement typically runs 1–2 hours. In many cases, for older pumps, replacing the entire pump (wet end + motor) makes more economic sense than just the motor." },
      { q: "Can I replace just the capacitor on my pool pump motor?", a: "Yes, if the capacitor is the only issue. Start and run capacitors are typically $15–$40 and can be replaced in 20–30 minutes. The capacitor is located in the capacitor cover on the back of the motor. Match the exact microfarad (µF) and voltage rating from the old capacitor. If replacement capacitor doesn't fix the start issue, the motor windings may also be compromised." },
    ],
    relatedSlugs: ["how-to-choose-variable-speed-pool-pump-commercial", "commercial-pool-equipment-checklist-complete-build-supply-list", "how-to-size-pool-salt-chlorinator"],
  },
  {
    slug: "commercial-pool-equipment-checklist-complete-build-supply-list",
    title: "Commercial Pool Equipment Checklist: Complete Pool Build Supply List",
    metaTitle: "Commercial Pool Equipment Checklist: Complete Build Supply List | Pool Supply Wholesalers",
    metaDescription: "The definitive commercial pool equipment checklist for contractors and facility managers. Covers pumps, filtration, heating, chemical systems, automation, lighting, and safety for commercial aquatic builds.",
    keywords: ["commercial pool equipment checklist", "pool build supply list", "commercial aquatic facility", "hotel pool equipment", "pool contractor checklist", "commercial pool construction"],
    category: "commercial",
    categoryLabel: "Commercial",
    author: "Pool Supply Wholesalers",
    authorTitle: "Commercial Pool Equipment Specialists",
    date: "2026-07-22",
    dateModified: "2026-09-04",
    readTime: "12 min read",
    tags: ["commercial pool equipment checklist", "pool build supply list", "commercial aquatic facility", "hotel pool equipment", "pool contractor checklist"],
    highlight: "Full Build Checklist",
    excerpt: "Planning a commercial aquatic facility or hotel pool build? Our definitive commercial pool equipment checklist covers pumps, filtration, heating, chemical systems, automation, lighting, and safety equipment — from 5,000+ active contractor accounts.",
    image: "/images/blog/commercial-pool-equipment-checklist-complete-build-supply-list.jpg",
    content: [
      { type: "paragraph", text: "Commercial pool builds have more moving parts than residential projects — literally. Miss one item in the equipment specification and you're either scrambling for a rush shipment during installation or writing a change order that blows the project budget. This checklist is based on specs from thousands of commercial projects we've supplied across hotel pools, apartment complexes, aquatic centers, and fitness facilities." },
      { type: "callout", variant: "info", title: "How to Use This Checklist", text: "Use this list during your pre-bid equipment specification phase. Every item marked with ✦ is required by most commercial health codes. Items marked ◆ are strongly recommended for commercial applications. Size specifications should be determined by a licensed pool engineer for each specific project." },
      { type: "h2", text: "1. Circulation & Pumping ✦" },
      { type: "bullets", items: [
        "Primary circulation pump — variable speed, commercial-rated (Pentair IntelliFloXF, Hayward TriStar VS, or Jandy FloPro VS)",
        "Backup/secondary pump — for commercial facilities with health code requirements for redundancy",
        "Pump pre-strainer basket",
        "Pump union connections (2\" or 2.5\")",
        "Pump shutoff valves (union ball valves)",
        "Pump mounting base pad or equipment rail",
        "Check valves on suction and return lines",
      ]},
      { type: "h2", text: "2. Filtration ✦" },
      { type: "bullets", items: [
        "Primary filter — cartridge or sand filter sized for flow rate (see sizing guide)",
        "Filter pressure gauge",
        "Filter sight glass (for sand filters with backwash)",
        "Backwash valve or multiport valve (sand) or clean-out manifold (cartridge)",
        "Backwash line to drain (sand filters)",
        "Filter shutoff valves",
        "Filter unions and unions bypass (for maintenance isolation)",
      ]},
      { type: "h2", text: "3. Heating ✦" },
      { type: "bullets", items: [
        "Primary pool heater — sized for pool volume and climate (gas or heat pump)",
        "Gas line connection — properly sized for BTU demand (licensed plumber required)",
        "Heater bypass valve set (for summer operation and freeze protection)",
        "Heater unions",
        "Flue and venting per manufacturer requirements",
        "Heater drain valve",
        "Pressure relief valve (required by code in most states)",
      ]},
      { type: "h2", text: "4. Sanitation & Chemical Systems ✦" },
      { type: "bullets", items: [
        "Salt chlorine generator OR chemical feeder system (with ORP/pH control)",
        "Automated chemical controller (pH/ORP probe system — required for commercial in most states)",
        "pH probe and ORP probe",
        "Acid dosing pump (for pH down — muriatic acid or CO2 system)",
        "Chlorine dosing pump or dry feed chlorinator (backup to primary sanitizer)",
        "Chemical storage and secondary containment (EPA required)",
        "Safety equipment: eyewash station, chemical-resistant gloves, aprons",
      ]},
      { type: "h2", text: "5. Automation & Controls ◆" },
      { type: "bullets", items: [
        "Pool automation control panel (Pentair EasyTouch, Hayward OmniLogic, or Jandy AquaLink RS)",
        "Remote display or indoor control station",
        "Mechanical room conduit and wiring harnesses",
        "Freeze protection sensor",
        "Flow sensor (for chemical controller accuracy)",
        "Temperature sensor for heater automation",
        "Emergency shutoff (GFCI protection per NEC code)",
      ]},
      { type: "h2", text: "6. Lighting ◆" },
      { type: "bullets", items: [
        "LED underwater pool lights — sized for pool perimeter (1 light per 200–300 sq ft of pool surface minimum)",
        "Pentair IntelliBrite or Hayward ColorLogic recommended for color/show features",
        "Niche and housing conduit (installed during construction — not an afterthought)",
        "Junction box per each light per code",
        "Low-voltage transformer (12V AC for most LED pool lights)",
        "GFCI protection circuit",
        "Deck lighting or underwater step lights (for safety)",
      ]},
      { type: "h2", text: "7. Safety & Accessibility ✦" },
      { type: "bullets", items: [
        "Anti-entrapment main drain covers (VGB-compliant — federally required)",
        "Anti-entrapment suction outlets (dual main drains minimum per VGB)",
        "Safety rope and float line (required by code for pools over specified depth)",
        "Stainless steel ladders and handrails (2 minimum for commercial pools)",
        "Life ring with throw line",
        "Emergency phone or call system (required for unmanned commercial pools in many states)",
        "Pool depth markers on decking and coping",
        "Handicap-accessible lift or ramp (ADA compliance — required for all new public pools)",
        "Pool fence and gate with self-latching latch (height varies by jurisdiction)",
      ]},
      { type: "h2", text: "8. Additional Items for Specific Facility Types" },
      { type: "h3", text: "Hotel & Resort Pools" },
      { type: "bullets", items: [
        "Spa/hot tub with separate pumps, heater, and blower",
        "Waterfall or water features with dedicated pump and automation",
        "Deck jets and bubblers",
        "Equipment room ventilation (required for indoor equipment with gas heaters)",
      ]},
      { type: "h3", text: "Aquatic Centers / Competition Pools" },
      { type: "bullets", items: [
        "High-rate filtration (multiple filter units in parallel)",
        "Surge tank or gutter system",
        "Competitive timing system conduit",
        "Starting block anchor conduit",
        "Lane line anchors",
      ]},
      { type: "h2", text: "9. Tools & Commissioning Items" },
      { type: "bullets", items: [
        "Pressure test pump for plumbing inspection",
        "ORP/pH test kit or professional photometer",
        "Clamp meter for motor amperage verification",
        "Flow meter for initial commissioning verification",
        "Pool startup chemical kit (sequesterant, startup shock, initial salt charge)",
      ]},
      { type: "h2", text: "Procuring Commercial Pool Equipment at Wholesale Pricing" },
      { type: "paragraph", text: "Pool Supply Wholesalers supplies all of the equipment categories above at wholesale to retail pricing for contractors, pool builders, and facility managers. We don't require a special membership or minimum order — just shop our catalog and all pricing reflects direct wholesale trade pricing, typically 20–40% below standard retail MSRP. For large commercial projects, contact our team to set up a commercial account with dedicated project pricing and priority fulfillment from our Nashville, LA, Dallas, and Orlando distribution centers." },
    ],
    faqs: [
      { q: "What permits are required for a commercial pool build?", a: "Commercial pool construction requires building permits from local authorities and typically reviews from the health department, electrical inspector, and plumbing inspector. Requirements vary significantly by state and municipality. Most jurisdictions require stamped engineering drawings for commercial pools. Always verify permit requirements before project kickoff." },
      { q: "How long does it take to get commercial pool equipment delivered?", a: "Pool Supply Wholesalers ships in-stock commercial equipment same-day from our four distribution hubs (Nashville, LA, Dallas, Orlando). Most continental US addresses receive orders within 2–5 business days. For large commercial projects with lead-time-sensitive equipment (large heaters, commercial automation panels), we recommend ordering 2–4 weeks before installation to allow for transit and any exchanges." },
    ],
    relatedSlugs: ["how-to-choose-variable-speed-pool-pump-commercial", "pentair-vs-hayward-vs-jandy-pool-heater-comparison-2026", "cartridge-filter-vs-sand-filter-pool-contractor-guide"],
  },
];

export function getArticleBySlug(slug: string): BlogArticle | undefined {
  return BLOG_ARTICLES.find(a => a.slug === slug);
}

export function getRelatedArticles(slugs: string[]): BlogArticle[] {
  return slugs.map(s => getArticleBySlug(s)).filter(Boolean) as BlogArticle[];
}
